export const FETCH_CHEAP_FLIGHT_DETAILS_BEGIN =
  'FETCH_CHEAP_FLIGHT_DETAILS_BEGIN';
export const FETCH_CHEAP_FLIGHT_DETAILS_SUCCESS =
  'FETCH_CHEAP_FLIGHT_DETAILS_SUCCESS';
export const FETCH_CHEAP_FLIGHT_DETAILS_FAILURE =
  'FETCH_CHEAP_FLIGHT_DETAILS_FAILURE';

export const FETCH_BUSINESS_FLIGHT_DETAILS_BEGIN =
  'FETCH_BUSINESS_FLIGHT_DETAILS_BEGIN';
export const FETCH_BUSINESS_FLIGHT_DETAILS_SUCCESS =
  'FETCH_BUSINESS_FLIGHT_DETAILS_SUCCESS';
export const FETCH_BUSINESS_FLIGHT_DETAILS_FAILURE =
  'FETCH_BUSINESS_FLIGHT_DETAILS_FAILURE';
